### ISSUE TITLE
Mean$1 is not a function

### ISSUE THREAD

**Issue by IgnatG** [Euphrasiologist/lwPhylo#1]
Hello

First of all, thank you for building this library - it's such a great tool!

I'm having some issues though when I'm trying to use the rectangular layout. I'm getting the following error in the console:
```
ERROR TypeError: mean$1 is not a function
    at getHorizontal (lwphylo.js:613)
```

this is what I'm using to load it:
```
treeString = "(((t13:0.7790112703,(t1:0.5220431073,t20:0.202340699):0.4815443838):0.3861331961,((t2:0.6067991166,t14:0.8800587754):0.9964700027,((((((t3:0.4080314219,t18:0.3741820636):0.009094102541,(t17:0.4135466665,t7:0.5426334133):0.3566526775):0.2189731502,(t19:0.1208170669,t5:0.1075042752):0.09370149556):0.5956722216,t6:0.8589682591):0.805277324,t15:0.8797334728):0.4385470266,t8:0.2457124488):0.426782382):0.365341407):0.2617313648,((t11:0.5743931823,t16:0.5058572968):0.2053716865,((t10:0.3861640515,t12:0.6367075392):0.739508104,(t4:0.6088686911,t9:0.02072311775):0.856660692):0.5528816739):0.4895316709);";
const parsedTree = lwphylo.readTree(treeString);
const rectPhylo = lwphylo.rectangleLayout(parsedTree);
```

This only happens when I'm trying to use the `rectangleLayout`. It works fine with `unrooted` and `radialLayout` and it draws the content as expected.

Also, I'm using npm to install it, `version 1.1.3`. And in my application, I'm loading the `lwphylo.js` file. However, if I'm loading the `lwphylo.min.js` I get a different error
`ERROR TypeError: o is not a function` - but I assume it's referring to the same issue
Any ideas where the problem is?

**Comment by Euphrasiologist** [comment]
Thank you for the comment! Much appreciated.

I did some digging, and found I had some rogue index.js files for some reason (me wrapping my head around the module process in js I guess). I've deleted those now and tested it in the browser and seems to work okay with your example.

I'll push version 1.1.4 to npm as soon as I can. 

Thank you for flagging this! Seems to be a pretty serious bug.

**Comment by IgnatG** [comment]
Thanks @Euphrasiologist ! I can confirm that the original issue was fixed!


I don't want to be a pain (sorry!) but there is a new problem now. 

The radial layout changed a little:
<img width="931" alt="radial" src="https://user-images.githubusercontent.com/6107088/112611425-b6f68a00-8e15-11eb-9e38-fe6c2b9d003a.png">

I did some digging and it looks like it's caused by a change inside the `src/radial/getArcs.js`, line 42 and 43. 

It was changed from 
```
 'start': reflectAngle(Math.**min**(pd[i].angle, sisterAngle(pd[i].parentId)), "Y"),
 'end': reflectAngle(Math.**max**(pd[i].angle, sisterAngle(pd[i].parentId)), "Y")
```
to

```
'start': reflectAngle(Math.**max**(pd[i].angle, sisterAngle(pd[i].parentId)), "Y"),
'end': reflectAngle(Math.**min**(pd[i].angle, sisterAngle(pd[i].parentId)), "Y")
```

Would you be able to double-check this, please?

**Comment by Euphrasiologist** [comment]
D'oh! And wow it looks funky! Not sure how that happened. No pain at all - I want to make it a better tool :)  I'll change that now, thanks for doing the hard work for me.

**Comment by Euphrasiologist** [comment]
I tested on: https://next.observablehq.com/@euphrasiologist/lwphylo-tutorial with the newest version, and it seems to work with the changes back. Let me know either way.

**Comment by IgnatG** [comment]
I've tried it now and yes, all looks good!
Thank you for your help!
