### ISSUE TITLE
Align labels in radial and unrooted trees

### ISSUE THREAD

**Issue by IgnatG** [Euphrasiologist/lwPhylo#2]
Hello

Is there a way to align the labels for radial (and unrooted) trees so they look similar to the second example?
See the first example to see what they currently look like.
p.s. I'm using the ``data.radii`` object and ``x0`` and ``y0`` keys to align inside the svg

![screenshot](https://user-images.githubusercontent.com/6107088/114707372-0dbef780-9d22-11eb-8aa9-7823a574cbb1.png)

**Comment by Euphrasiologist** [comment]
Hi,

Yes I can see that's annoying. I did try and make something a while back but never got around to finishing it. My line of thought is that you'd need some kind of angle (radians) for each label, which can then be fed into a rotate() function inside of `transform(rotate(....)...)` attribute of the text. I can't promise I'll get to this quickly, but I'll try something!

M

**Comment by IgnatG** [comment]
thank you! 
No rush - so whenever you get the chance

**Comment by Euphrasiologist** [comment]
https://observablehq.com/@euphrasiologist/lwphylo-tutorial 

A much more talented coder pointed me in the right direction on this one (thanks Rich!). See the radial figure in the updated tutorial.

M
